name: Deploy FHIR IG to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install SUSHI
      run: pwd & npm install -g fsh-sushi

    - name: Install Jekyll and Bundler
      run: |
        gem install --user-install bundler jekyll
        echo 'export PATH=$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH' >> $GITHUB_ENV
        export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"

    - name: Create input-cache directory
      run: pwd & mkdir -p ./input-cache
      
    - name: Give execute permissions to scripts
      run: chmod +x _updatePublisher.sh _genonce.sh

    - name: Update IG Publisher
      run: yes | ./_updatePublisher.sh

    - name: Run SUSHI to generate FHIR resources
      run: sushi .

    - name: Run IG Publisher using _genonce.sh
      run: ./_genonce.sh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
