name: Deploy FHIR IG to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install SUSHI
      run: npm install -g fsh-sushi

    - name: Install Jekyll
      run: gem install jekyll bundler

    - name: Give execute permissions to scripts
      run: chmod +x _updatePublisher.sh _genonce.sh

    - name: Update IG Publisher
      run: ./_updatePublisher.sh

    - name: Run SUSHI to generate FHIR resources
      run: sushi .

    - name: Run IG Publisher using _genonce.sh
      run: ./_genonce.sh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
