name: Deploy FHIR IG to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update the image to the latest publisher
      uses: docker://hl7fhir/ig-publisher-base:latest
      with:
        args: ./_updatePublisher.sh --force
    
    - name: Run sushi to generate the ig.ini file
      uses: docker://hl7fhir/ig-publisher-base:latest
      with:
        args: sushi

    - name: Run the IG publisher
      uses: docker://hl7fhir/ig-publisher-base:latest
      with:
        args: ./_genonce.sh -no-sushi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
